Repository DP2-C1-035/Acme-ANS-D04, pull requests merged in 2025-04, with the labels that each got.

#132 feat(): Store Aircraft information
  src/main/java/acme/entities/aircraft/Aircraft.java
  src/main/java/acme/entities/aircraft/AircraftStatus.java
Labels: enhancement, Information Requirement

#133 feat(): Service added to the datamodel
  src/main/java/acme/entities/airline/Airline.java
  src/main/java/acme/entities/service/Service.java
Labels: enhancement, Information Requirement

#129 D02-S2-R03:Store Customer Information
  src/main/java/acme/entities/customer/Customer.java
Labels: enhancement, Information Requirement

#134 feat(): review added to the datamodel
  src/main/java/acme/entities/review/Review.java
Labels: enhancement, Information Requirement

#135 feat():Add test data for 5 flight crew members
  src/main/resources/WEB-INF/data/sample/flight-crew-member.csv
Labels: Testing requirements, test

#136 feat(): D02 student #3 dashboard link added
  reports/Student #3/D02-S3-DashBoard_link.txt
Labels: Managerial requirements
